version: '3.8'

services:
  firefox-browser:
    build: .
    container_name: my-firefox-container
    ports:
      - "6901:6901"  # Web 访问端口
      - "5901:5901"  # VNC 客户端访问端口
    environment:
      - VNC_PW=password  # 设置您的VNC访问密码
      - URL=https://gitee.com/login # 设置您希望 Firefox 启动时打开的网站
    shm_size: '2g' # 增加共享内存大小，有助于浏览器稳定运行
