# 工作流的名称
name: Docker Image CI

# 触发工作流的事件
on:
  # 当有代码推送到 main 分支时触发
  push:
    branches: [ "main" ]
  # 允许手动触发
  workflow_dispatch:

# 定义一个名为 "build-and-push" 的作业 (Job)
jobs:
  build-and-push:
    # 指定作业运行的虚拟环境
    runs-on: ubuntu-latest

    # 定义作业的步骤
    steps:
      # 步骤 1: 检出代码
      # 使用官方的 checkout action 来获取仓库的最新代码
      - name: Check out the repo
        uses: actions/checkout@v4

      # 步骤 2: 登录到 Docker Hub
      # 使用我们存储在 GitHub Secrets 中的凭证
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 步骤 3: 登录到 GitHub Container Registry (ghcr.io)
      # GITHUB_TOKEN 是 GitHub Actions 自动提供的，具有推送到本仓库 ghcr.io 的权限
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 步骤 4: 提取 Docker 元数据
      # 这个 action 会自动生成镜像的标签 (tag) 和标签 (label)
      # 例如：latest, git-commit-sha 等
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ secrets.DOCKERHUB_USERNAME }}/firefox-browser
            ghcr.io/${{ github.repository }}

      # 步骤 5: 构建并推送到两个镜像仓库
      # 这个核心 action 会执行构建和推送操作
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          # 启用 build cache，可以显著加快后续构建速度
          cache-from: type=gha
          cache-to: type=gha,mode=max
